version: '3.8'
services:
  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=mechhub
    command: mongod --replSet rs0 --bind_ip_all
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0', members:[{_id:0, host:'localhost:27017'}]}) }" | mongosh
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mongodb://mongodb:27017/mechhub?replicaSet=rs0
    depends_on:
      mongodb:
        condition: service_healthy

volumes:
  mongodb_data:

