[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 100

[env]
PORT = "3000"
NODE_ENV = "production"

[http]
port = 3000

[runtime]
memory = 512

